### PR TITLE
Checks if there is a need for checks on installation

### PR DESCRIPTION
**Pull request by axelande**
I'm not 100% sure but this could solve the issue with not working on first installation

### CODE REVIEW

**Comment by m-kuhn** [comment]
Thanks.
Are you able to verify if this fixes the problem?

QOL Hint: to automate black etc, follow the steps on https://github.com/opengisch/qpip#contribute

**Comment by axelande** [comment]
I'm not sure, it might fix the issue for the "plugin" that required qpip (if that is in the path when qpip gets installed). But it does not solve the issue that QGIS needs a restart for additional installation so it might be just a temporary fix. I write might fix it since it will behave differently when I installed it via a zip file compared from plugins.qgis.org.

Any ideas why it does not work before QGIS gets restarted btw?

**Comment by m-kuhn** [comment]
Can you provide steps to reproduce?
I just tried the GeoDataFarm plugin, but if I'm not wrong, the released version doesn't currently require qpip (I see a message box with pip instructions)

**Comment by axelande** [comment]
Hi, Yeah I wanted to use qpip as a required plugin (but then it needs to work and not be experimental) in the mean time you can test it fetching the latest version. Comment out this line: https://github.com/axelande/geodatafarm3/blob/master/GeoDataFarm.py#L48 (that tries to the same thing behind the scen as qpip), uninstall some python package (e.g. reportlab) and remove this comment: https://github.com/axelande/geodatafarm3/blob/master/metadata.txt#L92 and zip the plugin and try to install it

**Comment by axelande** [comment]
This does not really solve the issue :(

**Pull request closed without merging**
